name: delivery
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0

  dio: ^5.3.2

  webview_flutter: ^4.4.1

  google_maps_flutter: ^2.5.0

  flutter_svg: ^2.0.7

  flutter_map: ^6.0.1

  get: 4.6.5

  image_picker: ^1.0.4

  camera: ^0.10.5+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/mhnf.jpg
    - assets/pizza.png
    - assets/burger.png
    - assets/burger_cover.jpg
    - assets/weather.svg
